export * from "./data-display";
export * from "./results-display";
export * from "./integrantes";
export * from "./regression-data-display";
export * from "./regression-results-display";
export * from "./calculate-regression-button";
export * from "./prediction-form";
export * from "./scatter-charts";
export * from "./navbar";
